pipeline {
    agent any
    stages {
        stage('Clean') {
            steps {
                cleanWs()
                // in groovy
                // echo "${env.WORKSPACE}"
                //in shell
                // sh 'echo $WORKSPACE'
                // in groovy script 
                // script {
                //     print env.WORKSPACE
                // }
            }
        }
        stage('clone') {
            environment {
                DB_PRESTA = credentials('DB_PRESTA')
                PRESTA_VAR = credentials('PRESTA_VAR')
            }
            steps {
                // sh "mv $DB_PRESTA ./Project-B-Its/prestashop/"
                // sh "mv $PRESTA_VAR ./Project-B-Its/prestashop/"
                sh "git clone https://github.com/Projetits/Project-B-Its.git"
                echo "Clonage du repo en cour..."
            }
        }
        stage('Build') {
            steps {
                sh "cd ./Project-B-Its/prestashop/ && docker compose up --env-file $DB_PRESTA"
                echo 'Installation de prestashop'
            }
        }
    }
}
   