version: '3.8'

services:
  authentication:
    build: ./authentication
    ports:
      - "5000:5000"
    networks:
      - prestashop-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_REFRESH_TOKEN_EXPIRE_MINUTES=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    secrets:
      - db_password

    depends_on:
      - db

  products:
    build: ./products
    ports:
      - "5001:5001"
    networks:
      - prestashop-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  reviews:
    build: ./reviews
    ports:
      - "5002:5002"
    networks:
      - prestashop-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mariadb:10.5  # Version corrigée, car la version 11.1 n'existe pas
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    secrets:
      - db_password
    networks:
      - prestashop-network
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - ./NGINX/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - prestashop-network
    depends_on:
      - prestashop-api

  prestashop-api:
    image: prestashop/prestashop:1.7.7.0
    command: 
      - /bin/bash
      - -c
      - |
        echo "ServerName localhost" >> /etc/apache2/apache2.conf
        apache2-foreground
    networks:
      - prestashop-network
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=${MYSQL_USER}
      - DB_PASSWD=${MYSQL_PASSWORD}
    depends_on:
      - db

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    networks:
      - prestashop-network
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix  # Base de données distincte pour Zabbix
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - db

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    networks:
      - prestashop-network
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=zabbix-server
    links:
      - zabbix-server

    depends_on:
      - zabbix-server

networks:
  prestashop-network:
    driver: bridge

volumes:
  db-data:

secrets:
  db_password:
    file: ./db_password.secret  # Chemin mis à jour pour pointer vers le répertoire des secrets
