pipeline {
    agent any
    stages {
        stage('Clean') {
            steps {
                cleanWs()
                // in groovy
                // echo "${env.WORKSPACE}"
                //in shell
                // sh 'echo $WORKSPACE'
                // in groovy script 
                // script {
                //     print env.WORKSPACE
                // }
            }
        }
        stage('clone') {

            environment {
                DB_PRESTA = credentials('DB_PRESTA')
                PRESTA_VAR = credentials('PRESTA_VAR')
            }
            steps {
                sh "git clone https://github.com/Projetits/Project-B-Its.git"
                sh('cp $DB_PRESTA ./Project-B-Its/prestashop/')
                sh('cp $PRESTA_VAR ./Project-B-Its/prestashop/')
                echo "Clonage du repo en cour..."
            }
        }
        stage('Build') {
            steps {
                sh "cd ./Project-B-Its/microA/app/ && docker compose up -d"
                echo 'Installation de prestashop & Installation de Micro-Services '
            }
        }
    }
    post {
        // Clean after build
        always {
            cleanWs(cleanWhenNotBuilt: false,
                    deleteDirs: true,
                    disableDeferredWipeout: true,
                    notFailBuild: true,
                    patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                                [pattern: 'db.env', type: 'INCLUDE'],
                                [pattern: 'presta.env', type: 'INCLUDE'],
                                [pattern: '.propsfile', type: 'EXCLUDE']])
        }
    }
}
