# Utilisez une image Python légère comme base
FROM python:3.9-slim

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers nécessaires dans le conteneur
COPY requirements.txt /app/

# Installez les dépendances
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Ajoutez Gunicorn à vos dépendances
RUN pip install gunicorn

# Copiez le reste du code dans le conteneur
COPY . .

# Définissez les variables d'environnement
ENV FLASK_RUN_PORT=5001 
ENV FLASK_APP=app.py 

# Commande pour exécuter l'application Flask avec Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5001", "app:app"]
