pipeline {
    agent any
    stages {

        stage('Clean') {
            steps {
                cleanWs()
                // in groovy
                // echo "${env.WORKSPACE}"
                //in shell
                // sh 'echo $WORKSPACE'
                // in groovy script 
                // script {
                //     print env.WORKSPACE
                // }
            }
        }
        stage('clone') {
            environment {
                PRESTA_DB_DEV = credentials('PRESTA_DB_DEV')
                PRESTA_MAIN_DEV = credentials('PRESTA_MAIN_DEV')
                PRESTA_API_KEY_DEV = credentials('PRESTA_API_KEY_DEV')
                PRESTA_PAT_DEV = credentials('PRESTA_PAT_DEV')
            }
            steps {
                echo "Clonage du repo en cour..."
                checkout scmGit(branches: [[name: '*/dev_jo_compose']],
                 extensions: [],
                 userRemoteConfigs: [[url: 'https://'+${PRESTA_PAT_DEV}+'@github.com/Projetits/Project-B-Its.git']]
                 )
                // sh "cd Project-B-Its"
                sh('pwd && ls -la')
                sh('cp ${PRESTA_DB_DEV} ./prestashop/')
                sh('cp ${PRESTA_MAIN_DEV} ./prestashop/')
                sh('cp ${PRESTA_API_KEY_DEV} ./prestashop/')
            }
        }
        stage('Build') {

            steps {
                sh ('ls -la')
                sh "cd ./prestashop/ && docker compose up -d"
                echo 'Installation de prestashop'
            }
        }

        stage('Test_clean') {
            steps {
                sh "docker exec -i api_manager python -m pytest ./tests"
                sh "docker container stop prestadb prestatest api_manager_dev"
                sh "docker container prune -f"
            }
        }
    }
}
   