pipeline {
    agent any
    stages {
        stage('Clean') {
            steps {
                cleanWs()
                // in groovy
                // echo "${env.WORKSPACE}"
                //in shell
                // sh 'echo $WORKSPACE'
                // in groovy script 
                // script {
                //     print env.WORKSPACE
                // }
            }
        }
        stage('clone') {
            
            environment {
                DB_PRESTA = credentials('DB_PRESTA')
                PRESTA_VAR = credentials('PRESTA_VAR')
                PRESTA_KEY_MNG = credentials('PRESTA_KEY_MNG')
            }
            steps {
                sh "git clone https://github.com/Projetits/Project-B-Its.git"
                sh "git checkout gestion_api"
                sh('cp $DB_PRESTA ./Project-B-Its/prestashop/')
                sh('cp $PRESTA_VAR ./Project-B-Its/prestashop/')
                sh('cp $PRESTA_KEY_MNG ./Project-B-Its/prestashop/')
                echo "Clonage du repo en cour..."
            }
        }
        stage('Build') {
            steps {
                sh "cd ./Project-B-Its/prestashop/ && docker compose up -d"
                echo 'Installation de prestashop'
            }
        }

        stage('Test_clean') {
            steps {
                sh "docker container stop some-mysql && docker container stop prestashop"
                sh "docker container prune"
            }
        }
    }
}
   