# Utilisez une image Python légère comme base
FROM python:3.9-slim

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers nécessaires dans le conteneur
COPY requirements.txt requirements.txt

# Installez les dépendances
RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir /app/logs
RUN chmod 777 /app/logs
# Copiez le reste du code dans le conteneur
COPY . .

# Définissez la variable d'environnement pour changer le port Flask
ENV FLASK_RUN_PORT=5010

# Définir les variables d'environnement
ENV FLASK_RUN_PORT=5010 
ENV FLASK_APP=app.py 

# Commande pour exécuter l'application Flask avec le port spécifié
CMD ["flask", "run", "--host=0.0.0.0", "--port=5010"]
